[workspace]
members = [
    "crates/tuner-core",
    "crates/tuner-dsp-algo",
    "crates/tuner-engine",
    "crates/tuner-dsp-native",
    "crates/tuner-dsp-web",
    "crates/tuner-dsp-embedded",
    "apps/tuner-cli",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

